/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.MarsRovers;

import main.java.MarsRovers.exception.ExplorationException;

import java.io.IOException;

public class MarsRoversApp {

    public static void main(String[] args) throws ExplorationException, IOException {
        MarsRoverExploration marsRoverExploration = new MarsRoverExploration();
        if(args != null && args.length>=1){
            marsRoverExploration.explore(args[0]);
        } else{
            throw new ExplorationException("Please provide input file to process for mars rover exploration");
        }
    }
}
